<?php

/*
|---------------------------------------------------------------
| 控制器
|---------------------------------------------------------------
| @package Q
|
*/
class Q_Controller_Front extends Q_Abstract_Front
{
    public static function run(Q_Request $request = null, Q_Response $response = null, $flush = false, $return = self::RETURN_NOT)
    {
        return parent::run($request, $response, $flush, $return); // TODO: Change the autogenerated stub
    }

}


